# Copyright 2026 Christopher Barber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Type stubs for the `_native` nanobind extension module (built from cpp/binding.cpp).
#

# THIS FILE IS GENERATED by `pixi run stubgen` (scripts/stubgen.py)
# DO NOT EDIT THIS FILE DIRECTLY!
# Instead update the logic `scripts/stubgen.py`
"""antlrope: Python binding over the official ANTLR4 C++ runtime"""

from collections.abc import Sequence

class AtnShape:
    @property
    def grammar_type(self) -> int: ...
    @property
    def num_states(self) -> int: ...
    @property
    def num_decisions(self) -> int: ...
    @property
    def num_rules(self) -> int: ...
    @property
    def max_token_type(self) -> int: ...
    def __repr__(self) -> str: ...

def atn_shape(serialized: Sequence[int]) -> AtnShape:
    """Deserialize a serialized ATN int list and return its shape."""

class SyntaxError:
    """
    A raw parse diagnostic produced by the native parser. The Python
    layer wraps these into [ParseError][antlrope.ParseError]
    exceptions on a listener's
    [syntax_errors][antlrope.FacadeListener.syntax_errors].
    """

    @property
    def line(self) -> int:
        """1-based line of the offending token."""

    @property
    def column(self) -> int:
        """0-based column of the offending token."""

    @property
    def start(self) -> int:
        """
        0-based codepoint offset of the offending token's first
        character (matching the event-stream offsets), or -1 when there
        is no token (e.g. a lexer error).
        """

    @property
    def stop(self) -> int:
        """
        0-based codepoint offset of the offending token's last
        character, inclusive, or -1 when there is no token.
        """

    @property
    def message(self) -> str:
        """ANTLR's human-readable error message."""

    def __repr__(self) -> str: ...

class LexerSpec:
    """
    A deserialized lexer specification (the grammar's vocabulary, name
    lists, and ATN) used by the native lex and parse entry points.
    Obtain one through a generated `<Grammar>EventListener` instead of
    constructing it directly.
    """

    def __init__(
        self,
        grammar_file_name: str,
        literal_names: Sequence[str],
        symbolic_names: Sequence[str],
        rule_names: Sequence[str],
        channel_names: Sequence[str],
        mode_names: Sequence[str],
        serialized: Sequence[int],
    ) -> None: ...

class ParserSpec:
    """
    A deserialized parser specification (the grammar's vocabulary,
    rule names, and ATN) used by the native parse entry points.
    Obtain one through a generated `<Grammar>EventListener` instead of
    constructing it directly.
    """

    def __init__(
        self,
        grammar_file_name: str,
        literal_names: Sequence[str],
        symbolic_names: Sequence[str],
        rule_names: Sequence[str],
        serialized: Sequence[int],
    ) -> None: ...

class StreamChunker:
    def __init__(
        self,
        lexer_spec: LexerSpec,
        path: str,
        delim_types: Sequence[int],
        where: int,
        channel: int | None,
        lenient: bool,
        trim: bool,
        block: int = 0,
    ) -> None: ...
    def next_batch(self, n: int) -> tuple[list[tuple[int, int, int, str]], bool]:
        """
        Pull up to n chunk records from the streaming token chunker.
        Returns (rows, more): rows is a list of (offset, line, column,
        text) tuples (whitespace trimmed unless trim=False; empty
        regions skipped) and more is False once the final region at
        EOF has been emitted.
        """

class StreamRuleChunker:
    def __init__(
        self,
        parser_spec: ParserSpec,
        lexer_spec: LexerSpec,
        path: str,
        rule_indices: Sequence[int],
        lenient: bool,
        block: int = 0,
    ) -> None: ...
    def next_batch(self, n: int) -> tuple[list[tuple[int, int, int, str]], bool]:
        """
        Pull up to n parsed-rule chunk records from the streaming rule
        chunker. Returns (rows, more): rows is a list of (offset, line,
        column, text) tuples and more is False once EOF (or a token that
        begins no candidate rule) is reached.
        """

class Token:
    def getType(self) -> int: ...
    def getText(self) -> str: ...
    def getLine(self) -> int: ...
    def getCharPositionInLine(self) -> int: ...

class ParseTree:
    pass

class RuleContext(ParseTree):
    def getRuleIndex(self) -> int: ...

class ParserRuleContext(RuleContext):
    def getStart(self) -> Token: ...
    def getStop(self) -> Token: ...

class TerminalNode(ParseTree):
    def getSymbol(self) -> Token: ...

class ErrorNode(TerminalNode):
    pass

class ParseTreeListener:
    def __init__(self) -> None: ...
    def visitTerminal(self, arg: TerminalNode, /) -> None: ...
    def visitErrorNode(self, arg: ErrorNode, /) -> None: ...
    def enterEveryRule(self, arg: ParserRuleContext, /) -> None: ...
    def exitEveryRule(self, arg: ParserRuleContext, /) -> None: ...

def parse_count(
    parser_spec: ParserSpec, lexer_spec: LexerSpec, text: str, start_rule: int
) -> dict:
    """
    Diagnostic: parse and walk the tree with a native counting
    listener, without calling into Python.
    """

def parse_walk(
    parser_spec: ParserSpec,
    lexer_spec: LexerSpec,
    text: str,
    start_rule: int,
    listener: ParseTreeListener,
) -> None:
    """
    Diagnostic fallback: parse and walk the tree, dispatching each
    node to a Python ParseTreeListener (slow per-node FFI path).
    """

def parse_events(
    parser_spec: ParserSpec,
    lexer_spec: LexerSpec,
    text: str,
    start_rule: int,
    rule_mask: Sequence[int] | None = None,
    token_mask: Sequence[int] | None = None,
) -> tuple[bytes, list[SyntaxError]]:
    """
    Parse and return (events, errors): a bulk flat int32 event buffer of
    4*N values (kind, payload, start, stop) as bytes, and a list of
    SyntaxError diagnostics collected during the parse. Optional
    rule_mask and token_mask (lists of indices to keep) filter events
    natively. The default stderr error listener is suppressed.
    """

def parse_stage_times(
    parser_spec: ParserSpec, lexer_spec: LexerSpec, text: str, start_rule: int
) -> dict:
    """
    Diagnostic: dict of per-stage seconds (input_decode, lex_fill,
    parse_tree, walk) plus the token, event, and codepoint counts.
    """

def lex(
    lexer_spec: LexerSpec, text: str, token_mask: Sequence[int] | None = None
) -> tuple[bytes, list[SyntaxError]]:
    """
    Run only the lexer and return (tokens, errors): a flat int32 buffer
    of 4*N values (type, channel, start, stop) as bytes (EOF omitted),
    and a list of SyntaxError diagnostics. Optional token_mask (list of
    token types to keep) drops the rest natively. The cheap stage used
    to chunk input for walk_parallel without a full parse.
    """

def rule_spans(
    parser_spec: ParserSpec,
    lexer_spec: LexerSpec,
    text: str,
    start_rule: int,
    rule_mask: Sequence[int] | None = None,
    outermost: bool = True,
) -> tuple[bytes, list[SyntaxError]]:
    """
    Parse (entirely in C++) and return (spans, errors): a flat int32
    buffer of 3*N values (rule_index, start, stop) for each parse-tree
    rule kept by rule_mask (None = all), plus a list of SyntaxError
    diagnostics. With outermost=True, the subtree of a matched rule is
    not searched, so only top-level occurrences are returned. Used for
    rule-based chunking.
    """
