# GENERATED by antlrope — do not edit by hand.
# antlrope-version: 1.0.2
# command: antlrope gen generated.SchemaParser Schema -o schema_listener.py
# rundir: .
# input: UXZ86QC3DnxOH2lvnWQz1lZgNv2lMaVz4w8IhuA_DkY  generated/SchemaParser.py
# input: UNbHNVdK-iEbuv-03hsnwFLHj2yU86f62uDm7AZTAao  generated/SchemaLexer.py
"""
Event-listener facade for the Schema grammar. Subclass SchemaEventListener,
override the callbacks you care about, then call .walk(text).
"""

from __future__ import annotations

from typing import ClassVar

from generated.SchemaLexer import SchemaLexer
from generated.SchemaParser import SchemaParser

from antlrope import FacadeListener


class SchemaEventListener(FacadeListener):
    ruleNames: ClassVar[list[str]] = [
        "schema",
        "definition",
        "messageDef",
        "field",
        "fieldType",
        "enumDef",
    ]
    START_RULE = 0  # schema
    _LEXER: ClassVar[type] = SchemaLexer
    _PARSER: ClassVar[type] = SchemaParser

    # token-type constants
    MESSAGE = 1
    ENUM = 2
    INT = 3
    STRING = 4
    BOOL = 5
    LBRACE = 6
    RBRACE = 7
    SEMI = 8
    COMMA = 9
    ID = 10
    WS = 11
    COMMENT = 12

    def enterSchema(self) -> None:
        pass

    def exitSchema(self) -> None:
        pass

    def enterDefinition(self) -> None:
        pass

    def exitDefinition(self) -> None:
        pass

    def enterMessageDef(self) -> None:
        pass

    def exitMessageDef(self) -> None:
        pass

    def enterField(self) -> None:
        pass

    def exitField(self) -> None:
        pass

    def enterFieldType(self) -> None:
        pass

    def exitFieldType(self) -> None:
        pass

    def enterEnumDef(self) -> None:
        pass

    def exitEnumDef(self) -> None:
        pass

    def visitTerminal(self, token_type: int, text: str) -> None:
        pass

    def visitError(self, token_type: int, text: str) -> None:
        pass
