# Copyright 2026 Christopher Barber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Origin metadata embedded in generated facades.

The `gen` subcommand writes a machine-parseable comment header recording the
antlrope version, the command used, the run directory (relative to the output
file), and a SHA256 of each input module file. `regen` and `up-to-date` parse it
back to re-run the command or to detect staleness. All fields are deterministic,
so regenerating is byte-identical until an input or the antlrope version changes.
"""

from __future__ import annotations

import base64
import hashlib
import importlib
import os
from typing import NamedTuple

# The first header line, identical whether or not the rest of the metadata is
# present, so a plain (metadata-free) facade and a full one share it.
BANNER = "# GENERATED by antlrope — do not edit by hand."

_VERSION_PREFIX = "# antlrope-version:"
_COMMAND_PREFIX = "# command:"
_RUNDIR_PREFIX = "# rundir:"
_INPUT_PREFIX = "# input:"


class Metadata(NamedTuple):
    """Origin metadata recorded in a generated facade's header."""

    version: str
    command: str
    rundir: str | None
    inputs: list[tuple[str, str]]  # (path relative to rundir, base64 SHA256)


def sha256_file(path: str | os.PathLike[str]) -> str:
    """Return the SHA256 of a file's bytes, url-safe base64 (unpadded, ~43 chars)."""
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for block in iter(lambda: fh.read(65536), b""):
            h.update(block)
    return base64.urlsafe_b64encode(h.digest()).decode("ascii").rstrip("=")


def relpath_or_abs(path: str, start: str) -> str:
    """`os.path.relpath`, falling back to the absolute path when there isn't one.

    On Windows there is no relative path between different drives (relpath
    raises `ValueError`). An absolute path keeps the origin header usable:
    `regen` and `up-to-date` join recorded paths with `os.path.join`, which yields
    the absolute path unchanged.
    """
    try:
        return os.path.relpath(path, start)
    except ValueError:
        return os.path.abspath(path)


def input_digests(*qualnames: str) -> list[tuple[str, str]]:
    """For each importable module path, return (cwd-relative file path, SHA256).

    Modules without a `__file__` (namespace or frozen) are skipped. A path with no
    relative form from the cwd (another Windows drive) is recorded absolute.
    """
    cwd = os.getcwd()
    out: list[tuple[str, str]] = []
    for qualname in qualnames:
        path = getattr(importlib.import_module(qualname), "__file__", None)
        if path:
            out.append((relpath_or_abs(path, cwd), sha256_file(path)))
    return out


def render(meta: Metadata) -> str:
    """Render `meta` as the generated file's comment header (no trailing newline)."""
    lines = [
        BANNER,
        f"{_VERSION_PREFIX} {meta.version}",
        f"{_COMMAND_PREFIX} {meta.command}",
    ]
    if meta.rundir is not None:
        lines.append(f"{_RUNDIR_PREFIX} {meta.rundir}")
    lines += [f"{_INPUT_PREFIX} {digest}  {path}" for path, digest in meta.inputs]
    return "\n".join(lines)


def parse(text: str) -> Metadata | None:
    """Extract a `Metadata` block from the leading comment lines of `text`.

    Returns `None` when there is no antlrope banner or the required version and command
    lines are absent (e.g. a facade generated without the CLI).
    """
    version: str | None = None
    command: str | None = None
    rundir: str | None = None
    inputs: list[tuple[str, str]] = []
    seen_banner = False
    for line in text.splitlines():
        if not line.startswith("#"):
            break  # the header is a contiguous comment block at the top of the file
        if line.startswith(BANNER):
            seen_banner = True
        elif line.startswith(_VERSION_PREFIX):
            version = line[len(_VERSION_PREFIX) :].strip()
        elif line.startswith(_COMMAND_PREFIX):
            command = line[len(_COMMAND_PREFIX) :].strip()
        elif line.startswith(_RUNDIR_PREFIX):
            rundir = line[len(_RUNDIR_PREFIX) :].strip()
        elif line.startswith(_INPUT_PREFIX):
            parts = line[len(_INPUT_PREFIX) :].strip().split(None, 1)
            if len(parts) == 2:
                inputs.append((parts[1], parts[0]))  # (path, digest)
    if not seen_banner or version is None or command is None:
        return None
    return Metadata(version=version, command=command, rundir=rundir, inputs=inputs)
