# GENERATED by antlrope — do not edit by hand.
# antlrope-version: 1.0.3
# command: antlrope gen generated.JSONParser JSON -o json_listener.py
# rundir: .
# input: SusfwMGNV4iJLef84xNKSUpRIxB9_Pkz68g7O_hr0_I  generated/JSONParser.py
# input: V2y8BYEkSjpvuUF1j1h26YN-PebFgSdusavVBsdw6jo  generated/JSONLexer.py
"""
Event-listener facade for the JSON grammar. Subclass JsonEventListener,
override the callbacks you care about, then call .walk(text).
"""

from __future__ import annotations

from typing import ClassVar

from generated.JSONLexer import JSONLexer
from generated.JSONParser import JSONParser

from antlrope import FacadeListener


class JsonEventListener(FacadeListener):
    ruleNames: ClassVar[list[str]] = ["json", "obj", "pair", "arr", "value"]
    START_RULE = 0  # json
    _LEXER: ClassVar[type] = JSONLexer
    _PARSER: ClassVar[type] = JSONParser

    # token-type constants
    T__0 = 1
    T__1 = 2
    T__2 = 3
    T__3 = 4
    T__4 = 5
    T__5 = 6
    T__6 = 7
    T__7 = 8
    T__8 = 9
    STRING = 10
    NUMBER = 11
    WS = 12

    def enterJson(self) -> None:
        pass

    def exitJson(self) -> None:
        pass

    def enterObj(self) -> None:
        pass

    def exitObj(self) -> None:
        pass

    def enterPair(self) -> None:
        pass

    def exitPair(self) -> None:
        pass

    def enterArr(self) -> None:
        pass

    def exitArr(self) -> None:
        pass

    def enterValue(self) -> None:
        pass

    def exitValue(self) -> None:
        pass

    def visitTerminal(self, token_type: int, text: str) -> None:
        pass

    def visitError(self, token_type: int, text: str) -> None:
        pass
