# Copyright 2026 Christopher Barber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Regenerates `src/antlrope/_native.pyi` and fixes up some type annotations.

This is invoked by `pixi run stubgen`.

nanobind's stubgen is responsible for generating the stub (header included)
but cannot correctly infer all return types and defaults to `object` in those cases.
This script runs stubgen and then patches up the header and return type annotations
for methods identified in RETURN_TYPES.
"""

from __future__ import annotations

import datetime
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STUB = ROOT / "src" / "antlrope" / "_native.pyi"

# Functions whose return nanobind reports as `object` (it can't infer
# `nb::make_tuple(...)`), with the real type to substitute.
RETURN_TYPES = {
    "parse_events": "tuple[bytes, list[SyntaxError]]",
    "lex": "tuple[bytes, list[SyntaxError]]",
    "rule_spans": "tuple[bytes, list[SyntaxError]]",
    # next_batch is a method on both StreamChunker and StreamRuleChunker, so it
    # matches more than once; the regex below is indentation-agnostic.
    "next_batch": "tuple[list[tuple[int, int, int, str]], bool]",
}

THIS_YEAR = datetime.date.today().year
COPYRIGHT_YEARS = f"2026-{THIS_YEAR}" if THIS_YEAR > 2026 else "2026"

# License header + maintenance note, prepended ahead of stubgen's module
# docstring (stubgen drops everything above it).
HEADER = f"""\
# Copyright {COPYRIGHT_YEARS} Christopher Barber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Type stubs for the `_native` nanobind extension module (built from cpp/binding.cpp).
#

# THIS FILE IS GENERATED by `pixi run stubgen` (scripts/stubgen.py)
# DO NOT EDIT THIS FILE DIRECTLY!
# Instead update the logic `scripts/stubgen.py`
"""


def main() -> int:
    subprocess.check_call(
        [
            sys.executable,
            "-m",
            "nanobind.stubgen",
            "-m",
            "antlrope._native",
            "-o",
            str(STUB),
        ]
    )

    text = STUB.read_text(encoding="utf-8")

    for name, ret in RETURN_TYPES.items():
        text, n = re.subn(
            rf"(def {re.escape(name)}\([^\n]*\)) -> object:",
            rf"\1 -> {ret}:",
            text,
        )
        if n < 1:
            raise SystemExit(
                f"stubgen post-process: expected at least one '{name}(...) -> object', "
                f"found {n}. nanobind output changed; update scripts/stubgen.py."
            )

    STUB.write_text(HEADER + text, encoding="utf-8")

    # nanobind's stubgen does not follow our formatting rules, so run the same
    # `ruff format` the rest of the tree uses (config from pyproject.toml).
    subprocess.check_call([sys.executable, "-m", "ruff", "format", str(STUB)])

    print(
        f"wrote {STUB.relative_to(ROOT)} (stubgen + hand edits + ruff format applied)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
